module.exports = {
    UNLOAD: "UNLOAD",
    LOAD: "LOAD",
    LOAD_DEFAULT: "LOAD_DEFAULT",
    CLICK_CLOSE_ATTACHED: "CLICK_CLOSE_ATTACHED",
    CLICK_CLOSE_DETACHED: "CLICK_CLOSE_DETACHED",
    ATTACH_INPUT: "ATTACH_INPUT",
    SET_INPUT_CURSOR: "SET_INPUT_CURSOR",
    SET_INPUT_VALUE: "SET_INPUT_VALUE",
    SELECT_SYMBOL: "SELECT_SYMBOL",
    SET_SYMBOLS: "SET_SYMBOLS",

    DEBUG: "DEBUG",

    SHOW_WARNING: "SHOW_WARNING",
    HIDE_WARNING: "HIDE_WARNING",
    GAMEPAD_EVENT: "GAMEPAD_EVENT"
};